debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "jetpackpony.tech"
watch = true
exposedByDefault = false

[acme]
email = "vfication@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
[[acme.domains]]
  main = "*.jetpackpony.tech"
  sans = ["jetpackpony.tech"]
[[acme.domains]]
  main = "*.a2b.space"
  sans = ["a2b.space"]